###################################################
### WARNING: This file is synced from katanomi/hack
### DO NOT CHANGE IT MANUALLY
###################################################
# https://docs.getwoke.tech/rules/
ignore_files:
  - .golangci.yaml
  - .build/*
  - catalog.yaml

# https://docs.getwoke.tech/ignore/
rules:
  - name: whitelist
    terms:
      - whitelist
      - white-list
    alternatives:
      - allowlist
    # severity: warn # disabled to show that error is the default
  - name: alauda
    terms:
      - alauda
    alternatives:
      - katanomi
