apiVersion: builds.katanomi.dev/v1alpha1
kind: Build
spec:
  workspaces:
    - description: |
        This workspace is shared among all the pipeline tasks to read/write common resources
      name: source
    - description: |
        Cache for go modules
      name: cache
      optional: true
  tasks:
    - name: commit-status
      timeout: 30m
      retries: 0
      taskRef:
        kind: ClusterTask
        name: katanomi-github-commit-status
      workspaces:
        - name: source
          workspace: source
      when: []
      params:
        - name: state
          value: success
        - name: target-url
          value: https://edge.alauda.cn/console-devops/workspace/devops/ci/update/katanomi-pkg-downstream-test
        - name: description
          value: 成功
  git:
    options:
      depth: 1
      timeout: 10m
      retries: 0
  runTemplate:
    spec:
      taskRunSpecs: []
